spring:
  application:
    name: Nexus-X
  data:
    redis:
      host: localhost
      port: 6379
      password: "19760129aaAA@"
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: -1
  datasource:
    url: jdbc:mysql://localhost:3306/nexus_x_db
    username: root
    password: 19760129
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: org.yuxun.x.nexusx.Entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: false
logging:
  level:
    com.baomidou.mybatisplus: debug
    org.apache.ibatis: info
server:
  port: 8888
