spring:
  application:
    name: Nexus-X
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: -1
  datasource:
    username: root
    password: 19760129
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nexus_x_db
mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: org.yuxun.x.nexusx.Entity
server:
  port: 8888
